const EXPENSE_CATEGORIES = {
  ACCOMMODATION: 'ACCOMMODATION',
  TRANSPORT: 'TRANSPORT',
  FOOD: 'FOOD',
  ACTIVITIES: 'ACTIVITIES',
  SHOPPING: 'SHOPPING',
  OTHER: 'OTHER'
};

const ACTIVITY_CATEGORIES = {
  SIGHTSEEING: 'SIGHTSEEING',
  FOOD: 'FOOD',
  ADVENTURE: 'ADVENTURE',
  CULTURE: 'CULTURE',
  SHOPPING: 'SHOPPING',
  NATURE: 'NATURE',
  ENTERTAINMENT: 'ENTERTAINMENT',
  OTHER: 'OTHER'
};

module.exports = {
  EXPENSE_CATEGORIES,
  ACTIVITY_CATEGORIES
};
