const EXPENSE_CATEGORIES = {
  TRANSPORT: 'TRANSPORT',
  STAY: 'STAY',
  ACCOMMODATION: 'ACCOMMODATION',
  ACTIVITY: 'ACTIVITY',
  ACTIVITIES: 'ACTIVITIES',
  MEAL: 'MEAL',
  FOOD: 'FOOD',
  SHOPPING: 'SHOPPING',
  OTHER: 'OTHER'
};

const ACTIVITY_CATEGORIES = {
  SIGHTSEEING: 'SIGHTSEEING',
  FOOD: 'FOOD',
  ADVENTURE: 'ADVENTURE',
  CULTURE: 'CULTURE',
  SHOPPING: 'SHOPPING',
  NATURE: 'NATURE',
  ENTERTAINMENT: 'ENTERTAINMENT',
  NIGHTLIFE: 'NIGHTLIFE',
  RELAXATION: 'RELAXATION',
  WELLNESS: 'WELLNESS',
  OTHER: 'OTHER'
};

module.exports = {
  EXPENSE_CATEGORIES,
  ACTIVITY_CATEGORIES
};
